Repository ever-co/ever-gauzy, pull requests merged in 2020-09, with the labels that each got.

#2250 feat: add webhook to trigger pulumi to update
  Jenkinsfile
Labels: type: devops

#2271 Feat/#2214 organization integration tests
  apps/gauzy-e2e/src/integration/AddOrganizationTest.ts
  apps/gauzy-e2e/src/integration/DeleteOrganizationTest.ts
  apps/gauzy-e2e/src/integration/RegisterTest.ts
  apps/gauzy-e2e/src/support/Base/pagedata/AddOrganizationPageData.ts
  apps/gauzy-e2e/src/support/Base/pagedata/DeleteOrganizationPageData.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/AddOrganizationPageObject.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/DeleteOrganizationPageObject.ts
  apps/gauzy-e2e/src/support/Base/pages/AddOrganization.po.ts
  apps/gauzy-e2e/src/support/Base/pages/DeleteOrganization.po.ts
  apps/gauzy-e2e/src/support/Base/utils/util.ts
  apps/gauzy/src/app/@theme/components/header/header.component.ts
Labels: type: tests

#2272 fix: change webhook to use master ref
  Jenkinsfile
Labels: type: bug :bug:, type: devops

#2287 feat: invite users e2e tests
  apps/gauzy-e2e/src/integration/InviteUserTest.ts
  apps/gauzy-e2e/src/support/Base/pagedata/InviteUserPageData.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/InviteUserPageObject.ts
  apps/gauzy-e2e/src/support/Base/pages/InviteUser.po.ts
  apps/gauzy-e2e/src/support/Base/utils/util.ts
Labels: type: tests

#2289 Feat/#1601 edit profile page
  apps/gauzy-e2e/src/integration/EditProfileTest.ts
  apps/gauzy-e2e/src/support/Base/pagedata/EditProfilePageData.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/EditProfilePageObject.ts
  apps/gauzy-e2e/src/support/Base/pages/EditProfile.po.ts
Labels: type: tests

#2295 feat: add new user e2e tests
  apps/gauzy-e2e/src/integration/AddUserTest.ts
  apps/gauzy-e2e/src/support/Base/pagedata/AddUserPageData.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/AddUserPageObject.ts
  apps/gauzy-e2e/src/support/Base/pages/AddUser.po.ts
Labels: type: tests

#2297 feat: add existing user e2e tests
  apps/gauzy-e2e/src/integration/AddExistingUserTest.ts
  apps/gauzy-e2e/src/support/Base/pagedata/AddExistingUserPageData.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/AddExistingUserPageObject.ts
  apps/gauzy-e2e/src/support/Base/pages/AddExistingUser.po.ts
  apps/gauzy-e2e/src/support/Base/utils/util.ts
Labels: type: tests

#2306 Feat/#1601 edit user e2e tests
  apps/gauzy-e2e/src/integration/EditProfileTest.ts
  apps/gauzy-e2e/src/integration/EditUserTest.ts
  apps/gauzy-e2e/src/support/Base/pagedata/EditUserPageData.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/EditProfilePageObject.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/EditUserPageObject.ts
  apps/gauzy-e2e/src/support/Base/pages/EditProfile.po.ts
  apps/gauzy-e2e/src/support/Base/pages/EditUser.po.ts
Labels: type: tests

#2307 feat: remove user e2e tests
  apps/gauzy-e2e/src/integration/RemoveUserTest.ts
  apps/gauzy-e2e/src/support/Base/pagedata/RemoveUserPageData.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/RemoveUserPageObject.ts
  apps/gauzy-e2e/src/support/Base/pages/RemoveUser.po.ts
Labels: type: tests

#2315 feat: manage invites e2e tests
  apps/gauzy-e2e/src/integration/ManageUserInvitesTest.ts
  apps/gauzy-e2e/src/support/Base/pagedata/ManageUserInvitesPageData.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/ManageUserInvitesPageObject.ts
  apps/gauzy-e2e/src/support/Base/pages/ManageUserInvites.po.ts
Labels: type: tests

#2321 Feat/#1601 templates e2e tests
  apps/api/src/app/core/seeds/data/default-email-templates/equipment-request/he/html.mjml
  apps/api/src/app/core/seeds/data/default-email-templates/invite-employee/ru/subject.hbs
  apps/api/src/app/core/seeds/data/default-email-templates/invite-organization-client/he/subject.hbs
  apps/api/src/app/core/seeds/data/default-email-templates/invite-organization-client/ru/subject.hbs
  apps/api/src/app/core/seeds/data/default-email-templates/invite-user/ru/subject.hbs
  apps/api/src/app/core/seeds/data/default-email-templates/password/ru/subject.hbs
  apps/api/src/app/core/seeds/data/default-email-templates/timesheet-submit/en/subject.hbs
  apps/api/src/app/core/seeds/data/default-email-templates/welcome-user/he/subject.hbs
  apps/api/src/app/core/seeds/data/default-email-templates/welcome-user/ru/subject.hbs
  apps/gauzy-e2e/src/integration/EmailTempatesTest.ts
  apps/gauzy-e2e/src/support/Base/pagedata/EmailTempatesPageData.ts
Labels: type: tests

#2325 feat: refactored e2e tests
  apps/gauzy-e2e/src/integration/EmailTempatesTest.ts
  apps/gauzy-e2e/src/integration/ManageUserInvitesTest.ts
Labels: type: tests

#2328 feat: organization tags e2e tests
  apps/gauzy-e2e/src/integration/OrganizationTagsTest.ts
  apps/gauzy-e2e/src/support/Base/pagedata/OrganizationTagsPageData.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationTagsPageObject.ts
  apps/gauzy-e2e/src/support/Base/pages/OrganizationTags.po.ts
Labels: type: tests
