Repository ever-co/ever-gauzy, pull requests merged in 2020-07, with the labels that each got.

#1606 fix: auth github, and add to gauzy web environment
  .scripts/configure.ts
  apps/api/package.json
  apps/api/src/app/auth/auth.controller.ts
  apps/api/src/app/auth/auth.module.ts
  apps/api/src/app/auth/github.strategy.ts
  apps/api/src/app/auth/guard/github-auth-guard.ts
  apps/api/src/environments/IGithubConfig.ts
  apps/api/src/environments/environment.prod.ts
  apps/api/src/environments/environment.ts
  apps/gauzy/src/app/@core/auth/auth.module.ts
  apps/gauzy/src/environments/environment.ts
  apps/gauzy/src/environments/model.ts
Labels: type: enhancement ✨

#1622 Fix nginx not serving static files properly
  .deploy/webapp/nginx.conf
Labels: type: devops

#1661 fix: microsoft auth, provider and set the environment for gauzy website
  .scripts/configure.ts
  apps/api/package.json
  apps/api/src/app/auth/auth.controller.ts
  apps/api/src/app/auth/microsoft.strategy.ts
  apps/api/src/environments/IMicrosoftConfig.ts
  apps/api/src/environments/environment.prod.ts
  apps/api/src/environments/environment.ts
  apps/gauzy/src/app/@core/auth/auth.module.ts
  apps/gauzy/src/environments/environment.ts
  apps/gauzy/src/environments/model.ts
Labels: type: enhancement ✨

#1734 Feature/auth0
  .scripts/configure.ts
  apps/api/package.json
  apps/api/src/app/auth/auth.controller.ts
  apps/api/src/app/auth/auth.module.ts
  apps/api/src/app/auth/auth0.strategy.ts
  apps/api/src/environments/IAuth0Config.ts
  apps/api/src/environments/environment.prod.ts
  apps/api/src/environments/environment.ts
  apps/api/src/environments/ienvironment.ts
  apps/gauzy/src/environments/environment.ts
  apps/gauzy/src/environments/model.ts
Labels: type: enhancement ✨

#1765 Add Dockerfile for Windows and Linux builds
  .deploy/desktop/Dockerfile.linux
  .deploy/desktop/Dockerfile.win
Labels: type: devops

#1772 feat/jenkins_pipeline
  Jenkinsfile
  docker-compose.demo.yml
Labels: type: devops

#1796 feat/jenkins-ecr
  Jenkinsfile
Labels: type: devops

#1797 Fix parsing issues with Jenkinsfile
  Jenkinsfile
Labels: type: devops

#1800 Final improvements for Jenkins Pipeline
  Jenkinsfile
Labels: type: devops

#1813 Fixed parsing and security issues.
  Jenkinsfile
Labels: type: devops

#1820 Configure GitHub Actions for desktop builds
  .github/workflows/desktop-app.yml
Labels: type: devops

#1842 feat/jenkins-github-integration
  Jenkinsfile
Labels: type: devops

#1850 Fix JSON parsing issues
  .dockerignore
  Jenkinsfile
Labels: type: devops

#1855 Implement pending commit status while Jenkins runs
  Jenkinsfile
Labels: type: devops

#1856 Fix typo in Jenkinsfile.
  Jenkinsfile
Labels: type: devops

#1890 Fix Desktop App builds on GitHub Actions
  .github/workflows/desktop-app.yml
Labels: type: bug :bug:, type: devops
