Repository ever-co/ever-gauzy, pull requests merged in 2020-08, with the labels that each got.

#1979 Use PM2 instead of bare nodeJS for the CMD
  .deploy/api/Dockerfile
Labels: type: devops

#1977 Automate tagging when pushed to master
  .github/workflows/desktop-app.yml
Labels: type: devops

#2150 feat: added fields to multiple entities
  apps/api/src/app/contact/contact.entity.ts
  apps/api/src/app/organization-projects/organization-projects.entity.ts
  apps/api/src/app/organization/organization.entity.ts
  apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.html
  apps/gauzy/src/app/pages/contacts/contact-mutation/contact-mutation.component.ts
  apps/gauzy/src/app/pages/contacts/contact.component.html
  apps/gauzy/src/app/pages/contacts/contact.component.ts
  apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.html
  apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.ts
  apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.html
  apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-other-settings/edit-organization-other-settings.component.ts
  apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.html
  apps/gauzy/src/app/pages/projects/projects-mutation/projects-mutation.component.ts
  apps/gauzy/src/app/pages/projects/projects.component.html
  apps/gauzy/src/app/pages/projects/projects.component.ts
  apps/gauzy/src/app/pages/projects/projects.module.ts
  apps/gauzy/src/assets/i18n/en.json
  libs/models/src/lib/contact.model.ts
  libs/models/src/lib/organization-projects.model.ts
  libs/models/src/lib/organization.model.ts
Labels: type: enhancement ✨

#2186 fix: missing translations
  apps/gauzy/src/assets/i18n/en.json
Labels: type: bug :bug:

#2189 fix: edit estimate error
  apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts
Labels: type: bug :bug:

#2197 fix: improve demo docker-compose file
  docker-compose.demo.yml
Labels: type: devops

#2217 fix: delete invoice payment error
  apps/gauzy/src/app/pages/invoices/invoice-payments/payments.component.ts
Labels: type: bug :bug:

#2219 fix: delete payments payment error
  apps/gauzy/src/app/pages/payments/payments.component.ts
Labels: type: bug :bug:

#2221 Fix/#2220 proposal tags overlapping
  apps/gauzy/src/app/pages/proposals/proposal-details/proposal-details.component.scss
Labels: type: bug :bug:

#2227 feat: add pulumi to CircleCI
  .circleci/config.yml
Labels: type: devops

#2240 Fix/#2239 grid layout styling
  apps/gauzy/src/app/@shared/card-grid/card-grid.component.html
  apps/gauzy/src/app/@shared/card-grid/card-grid.component.scss
  apps/gauzy/src/app/@shared/card-grid/card-grid.component.ts
  apps/gauzy/src/app/pages/invoices/invoices.component.html
  apps/gauzy/src/app/pages/invoices/invoices.component.scss
Labels: type: bug :bug:

#2243 fix: tasks grid layout buttons disabled
  apps/gauzy/src/app/pages/tasks/components/task/task.component.html
Labels: type: bug :bug:

#2245 fix: employees manage interviews error
  apps/gauzy/src/app/pages/candidates/manage-candidate-interviews/interview-panel/interview-panel.component.html
Labels: type: bug :bug:

#2249 fix: delete sprint dialog broken styling
  apps/gauzy/src/app/pages/tasks/components/task/task-settings/project-view/tasks-sprint-settings-view/tasks-sprint-settings-view.component.html
Labels: type: bug :bug:

#2252 fix: delete timeslot not registered on frontend
  apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
  apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
Labels: type: bug :bug:
