Repository ever-co/ever-gauzy, pull requests merged in 2022-02, with the labels that each got.

#4071 Feat/#3964 view respective reports link
  apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
  apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.scss
  apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
  apps/gauzy/src/app/pages/reports/all-report/all-report.module.ts
  apps/gauzy/src/app/pages/reports/all-report/all-report/all-report.component.html
  apps/gauzy/src/app/pages/reports/all-report/all-report/all-report.component.scss
  apps/gauzy/src/app/pages/reports/apps-urls-report/apps-urls-report/apps-urls-report.component.ts
  apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.html
  apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.ts
  apps/gauzy/src/assets/i18n/en.json
Labels: Changes requested

#4087 Bug/#4084 missing next previous icon date picker reports
  apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.html
  apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.scss
  apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.html
  apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report/time-limit-report.component.html
Labels: Changes requested

#4108 Feat / Implemented feature-toggle dto validations
  packages/core/src/feature/dto/create-feature-toggle.dto.ts
  packages/core/src/feature/dto/index.ts
  packages/core/src/feature/feature-toggle.controller.ts
Labels: validators

#4112 Feature / Implemented income dto validation
  packages/core/src/income/dto/create-income.dto.ts
  packages/core/src/income/dto/income.dto.ts
  packages/core/src/income/dto/index.ts
  packages/core/src/income/dto/update-income.dto.ts
  packages/core/src/income/income.controller.ts
Labels: validators

#4116 Feature/ Implemented dto validation for expense
  packages/core/src/expense/dto/create-expense.dto.ts
  packages/core/src/expense/dto/expense.dto.ts
  packages/core/src/expense/dto/index.ts
  packages/core/src/expense/dto/update-expense.dto.ts
  packages/core/src/expense/expense.controller.ts
Labels: validators

#4121 Feature / Implemented dto validation for payments
  packages/core/src/payment/dto/create-payment.dto.ts
  packages/core/src/payment/dto/index.ts
  packages/core/src/payment/dto/payment.dto.ts
  packages/core/src/payment/dto/update-payment.dto.ts
  packages/core/src/payment/payment.controller.ts
Labels: validators

#4122 Feature / Implemented dto validation for goal
  packages/core/src/goal/dto/create-goal.dto.ts
  packages/core/src/goal/dto/goal.dto.ts
  packages/core/src/goal/dto/index.ts
  packages/core/src/goal/dto/update-goal.dto.ts
  packages/core/src/goal/goal.controller.ts
Labels: validators

#4125 Feature / Implemented dto validation for goal general setting
  packages/core/src/goal-general-setting/dto/create-goal-general-setting.dto.ts
  packages/core/src/goal-general-setting/dto/goal-general-setting.dto.ts
  packages/core/src/goal-general-setting/dto/index.ts
  packages/core/src/goal-general-setting/dto/update-goal-general-setting.dto.ts
  packages/core/src/goal-general-setting/goal-general-setting.controller.ts
Labels: validators

#4132 Feature / Implemented dto validitions for keyresult
  packages/core/src/keyresult/dto/create-keyresult.dto.ts
  packages/core/src/keyresult/dto/index.ts
  packages/core/src/keyresult/dto/keyresult-bulk-input.dto.ts
  packages/core/src/keyresult/dto/keyresult.dto.ts
  packages/core/src/keyresult/dto/update-keyresult.dto.ts
  packages/core/src/keyresult/keyresult.controller.ts
Labels: validators

#4135 Feature / Implemented dto validation for proposal routes
  packages/core/src/proposal/dto/create-proposal.dto.ts
  packages/core/src/proposal/dto/index.ts
  packages/core/src/proposal/dto/proposal.dto.ts
  packages/core/src/proposal/dto/update-proposal.dto.ts
  packages/core/src/proposal/proposal.controller.ts
Labels: validators, Changes requested

#4143 Feat/ Disallow switching to future periods in reports
  apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/gauzy-range-picker.component.html
  apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/gauzy-range-picker.component.ts
Labels: Changes requested

#4142 Feature / Implemented dto validations for organization team
  packages/core/src/organization-team/dto/create-organization-team.dto.ts
  packages/core/src/organization-team/dto/index.ts
  packages/core/src/organization-team/dto/organization-team.dto.ts
  packages/core/src/organization-team/dto/update-organization-team.dto.ts
  packages/core/src/organization-team/organization-team.controller.ts
Labels: validators, Changes requested

#4137 Feature / Implemented dto validations for invoices
  packages/contracts/src/invoice-item.model.ts
  packages/core/src/invoice-estimate-history/dto/create-invoice-estimate-history.dto.ts
  packages/core/src/invoice-estimate-history/dto/index.ts
  packages/core/src/invoice-estimate-history/dto/invoice-estimate-history.dto.ts
  packages/core/src/invoice-item/dto/create-invoice-item.dto.ts
  packages/core/src/invoice-item/dto/index.ts
  packages/core/src/invoice-item/dto/invoice-item.dto.ts
  packages/core/src/invoice-item/invoice-item.entity.ts
  packages/core/src/invoice-item/invoice-item.seed.ts
  packages/core/src/invoice/dto/create-invoice.dto.ts
  packages/core/src/invoice/dto/index.ts
  packages/core/src/invoice/dto/invoice.dto.ts
  packages/core/src/invoice/dto/update-invoice.dto.ts
  packages/core/src/invoice/invoice.controller.ts
Labels: validators, Changes requested

#4147 Fix/ Dark theme should work fine
  apps/gauzy/src/app/@shared/report/activities-report-grid/activities-report-grid.component.scss
  apps/gauzy/src/app/@shared/report/amounts-owed-grid/amounts-owed-grid.component.scss
  apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.scss
  apps/gauzy/src/app/@shared/report/expenses-report-grid/expenses-report-grid.component.scss
  apps/gauzy/src/app/@shared/report/payment-report-grid/payment-report-grid.component.scss
  apps/gauzy/src/app/@theme/styles/report.scss
  apps/gauzy/src/app/pages/accounting-templates/accounting-templates.component.html
  apps/gauzy/src/app/pages/accounting-templates/accounting-templates.component.scss
  apps/gauzy/src/app/pages/reports/client-budgets-report/client-budgets-report/client-budgets-report.component.scss
  apps/gauzy/src/app/pages/reports/manual-time/manual-time/manual-time.component.scss
  apps/gauzy/src/app/pages/reports/project-budgets-report/project-budgets-report/project-budgets-report.component.scss
  apps/gauzy/src/app/pages/reports/time-limit-report/time-limit-report/time-limit-report.component.scss
  apps/gauzy/src/app/pages/reports/weekly-time-reports/weekly-time-reports/weekly-time-reports.component.scss
  packages/core/src/core/seeds/data/default-accounting-templates/estimate/bg/estimate.mjml
  packages/core/src/core/seeds/data/default-accounting-templates/estimate/en/estimate.mjml
  packages/core/src/core/seeds/data/default-accounting-templates/estimate/he/estimate.mjml
  packages/core/src/core/seeds/data/default-accounting-templates/estimate/ru/estimate.mjml
  packages/core/src/core/seeds/data/default-accounting-templates/invoice/bg/invoice.mjml
  packages/core/src/core/seeds/data/default-accounting-templates/invoice/en/invoice.mjml
  packages/core/src/core/seeds/data/default-accounting-templates/invoice/he/invoice.mjml
  packages/core/src/core/seeds/data/default-accounting-templates/invoice/ru/invoice.mjml
  packages/core/src/core/seeds/data/default-accounting-templates/receipt/bg/receipt.mjml
  packages/core/src/core/seeds/data/default-accounting-templates/receipt/en/receipt.mjml
  packages/core/src/core/seeds/data/default-accounting-templates/receipt/he/receipt.mjml
  packages/core/src/core/seeds/data/default-accounting-templates/receipt/ru/receipt.mjml
Labels: Changes requested

#4156 Feature / Implemented dto validations for invoice items
  packages/core/src/invoice-item/dto/index.ts
  packages/core/src/invoice-item/dto/invoice-item-bulk-input.dto.ts
  packages/core/src/invoice-item/invoice-item.controller.ts
Labels: validators

#4157 Feature / Improved dto validations for invoice
  packages/core/src/invoice/dto/invoice.dto.ts
Labels: validators

#4158 Bug / Fixed name required for Goal creation
  apps/gauzy/src/app/pages/goals/edit-objective/edit-objective.component.html
  apps/gauzy/src/app/pages/goals/edit-objective/edit-objective.component.ts
Labels: validators

#4159 Bug / Fixed dto validations for invoice
  apps/gauzy/src/app/pages/invoices/invoice-edit/invoice-edit.component.ts
  packages/core/src/invoice/dto/create-invoice.dto.ts
  packages/core/src/invoice/dto/discount-invoice.dto.ts
  packages/core/src/invoice/dto/invoice.dto.ts
  packages/core/src/invoice/dto/tax-invoice.dto.ts
  packages/core/src/invoice/dto/update-invoice.dto.ts
  packages/core/src/invoice/invoice.controller.ts
  packages/core/src/tags/dto/index.ts
  packages/core/src/tags/dto/relational-tag.dto.ts
Labels: validators, Changes requested

#4161 NOT MERGE YET : Feature / Implemented dto validation for keyresult update
  apps/gauzy/src/app/@core/services/keyresult-update.service.ts
  packages/contracts/src/goals.model.ts
  packages/core/src/keyresult-update/dto/create-keyresult-update.dto.ts
  packages/core/src/keyresult-update/dto/index.ts
  packages/core/src/keyresult-update/dto/keyresult-update.dto.ts
  packages/core/src/keyresult-update/dto/update-keyresult-update.dto.ts
  packages/core/src/keyresult-update/keyresult-update.controller.ts
  packages/core/src/keyresult-update/keyresult-update.entity.ts
Labels: validators

#4169 Bug / Created and Implemented new endpoint to Accept and Reject Estimates
  apps/gauzy/src/app/@core/services/invoices.service.ts
  apps/gauzy/src/app/pages/invoices/invoices-received/invoices-received.component.ts
  packages/core/src/invoice/dto/index.ts
  packages/core/src/invoice/dto/update-estimate-invoice.dto.ts
  packages/core/src/invoice/invoice.controller.ts
Labels: type: bug :bug:

#4174 Feature / Implemented dto validations for keyresult template
  packages/core/src/goal-kpi-template/dto/index.ts
  packages/core/src/goal-kpi-template/dto/relational-gloal-kpi-template.dto.ts
  packages/core/src/goal-template/dto/index.ts
  packages/core/src/goal-template/dto/relational-goal-template.dto.ts
  packages/core/src/keyresult-template/dto/create-keyresult-template.dto.ts
  packages/core/src/keyresult-template/dto/index.ts
  packages/core/src/keyresult-template/dto/keyresult-template.dto.ts
  packages/core/src/keyresult-template/keyresult-template.controller.ts
Labels: validators, Changes requested

#4167 Feat/Improve date range selector (Time Tracking Dashboard)
  apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/arrow/strategies/concrete/future.strategy.ts
  apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/arrow/strategies/concrete/index.ts
  apps/gauzy/src/app/@shared/timesheet/gauzy-range-picker/gauzy-range-picker.component.ts
  apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.html
  apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.scss
  apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
  apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.module.ts
  packages/contracts/src/timesheet-statistics.model.ts
Labels: Changes requested

#4177 Bug / Made payment method to be a valid enum value
  packages/core/src/payment/dto/payment.dto.ts
Labels: type: bug :bug:, validators

#4175 Feature / Implemented dto validations for organization position
  packages/contracts/src/organization-positions.model.ts
  packages/core/src/organization-position/dto/index.ts
  packages/core/src/organization-position/dto/organization-position.dto.ts
  packages/core/src/organization-position/dto/update-organization-position.dto.ts
  packages/core/src/organization-position/organization-position.controller.ts
  packages/core/src/organization-position/organization-position.entity.ts
Labels: validators

#4190 Bug/ Fixed estimate changing status
  apps/gauzy/src/app/@core/services/invoices.service.ts
  apps/gauzy/src/app/pages/invoices/invoices.component.ts
  packages/core/src/invoice/dto/index.ts
  packages/core/src/invoice/dto/update-estimate-status.dto.ts
  packages/core/src/invoice/invoice.controller.ts
Labels: type: bug :bug:

#4192 Bug / Fixed convert estimate to invoice
  apps/gauzy/src/app/@core/services/invoices.service.ts
  apps/gauzy/src/app/pages/invoices/invoices.component.ts
  packages/core/src/invoice/dto/index.ts
  packages/core/src/invoice/dto/update-estimate-status.dto.ts
  packages/core/src/invoice/dto/update-invoice-action.dto.ts
  packages/core/src/invoice/invoice.controller.ts
Labels: type: bug :bug:, Changes requested

#4195 Bug / Fixed Estimate update extra options
  apps/gauzy/src/app/pages/invoices/add-internal-note/add-internal-note.component.ts
  apps/gauzy/src/app/pages/invoices/invoice-email/invoice-email-mutation.component.ts
  apps/gauzy/src/app/pages/invoices/invoices.component.ts
  packages/core/src/invoice/dto/index.ts
  packages/core/src/invoice/dto/update-estimate-invoice.dto.ts
  packages/core/src/invoice/dto/update-invoice-action.dto.ts
  packages/core/src/invoice/invoice.entity.ts
Labels: type: bug :bug:

#4198 Bug / Fixed payment issue
  apps/gauzy/src/app/pages/invoices/invoice-payments/payments.component.ts
  packages/core/src/invoice/dto/update-invoice-action.dto.ts
Labels: type: bug :bug:

#4210 Bug : Fixed Expense update Bug
  apps/gauzy/src/app/pages/expenses/expenses.component.ts
  packages/contracts/src/expense.model.ts
Labels: type: bug :bug:

#4211 Feat/#4207 update generated pdf
  apps/gauzy/src/app/@shared/pipes/index.ts
  apps/gauzy/src/app/@shared/pipes/safe/safe.pipe.spec.ts
  apps/gauzy/src/app/@shared/pipes/safe/safe.pipe.ts
  apps/gauzy/src/app/@shared/pipes/text.pipe.ts
  apps/gauzy/src/app/pages/invoices/invoice-pdf/invoice-pdf.component.ts
  packages/core/src/invoice/generate-invoice-pdf.ts
  packages/core/src/invoice/pdfmaker.service.ts
Labels: hold, Changes requested

#4215 Bug : Fixed Proposal change Status
  apps/gauzy/src/app/@core/services/proposals.service.ts
  apps/gauzy/src/app/pages/proposals/proposals.component.ts
  packages/core/src/proposal/dto/index.ts
  packages/core/src/proposal/dto/update-proposal-action.dto.ts
  packages/core/src/proposal/proposal.controller.ts
Labels: type: bug :bug:, Changes requested

#4220 Bug / Solved edit proposal bug
  apps/gauzy/src/app/pages/proposals/proposal-edit/proposal-edit.component.ts
Labels: type: bug :bug:

#4225 Bug / Fix edit main organization
  apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-main/edit-organization-main.component.ts
Labels: type: bug :bug:

#4233 Fixed / Edit shared organization
  apps/gauzy/src/app/pages/organizations/edit-organization/edit-organization-settings/edit-organization-location/edit-organization-location.component.ts
  apps/gauzy/src/app/share/organization/organization.component.ts
Labels: type: bug :bug:

#4249 Fixed / Adjusted edit candidate request payload to new validated endpoints
  apps/gauzy/src/app/pages/candidates/edit-candidate/edit-candidate-profile/edit-candidate-profile.component.ts
Labels: type: bug :bug:

#4247 Feature / Implemented dto validation for candidate source
  apps/gauzy/src/app/@core/services/candidates.service.ts
  apps/gauzy/src/app/@shared/candidate/candidate-mutation/candidate-mutation.component.ts
  apps/gauzy/src/app/pages/candidates/candidates.component.ts
  apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
  packages/core/src/candidate-source/candidate-source.controller.ts
  packages/core/src/candidate-source/dto/candidate-source-bulk-input.dto.ts
  packages/core/src/candidate-source/dto/create-candidate-source.dto.ts
  packages/core/src/candidate-source/dto/index.ts
  packages/core/src/candidate-source/dto/update-candidate-source.dto.ts
Labels: validators

#4283 Fixed / Duplicated recurring expense sub menu into accounting
  apps/gauzy/src/app/pages/pages-routing.module.ts
  apps/gauzy/src/app/pages/pages.component.ts
Labels: type: bug :bug:

#4261 Feature / Implemented dto validation for employee recurring expense
  apps/gauzy/src/app/@shared/expenses/expenses-mutation/expenses-mutation.component.html
  apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.html
  apps/gauzy/src/app/@shared/expenses/recurring-expense-mutation/recurring-expense-mutation.component.ts
  packages/core/src/currency/dto/index.ts
  packages/core/src/currency/dto/relational-currency.dto.ts
  packages/core/src/database/migrations/1646056129050-AlterEmployeeRecurringExpenseTable.ts
  packages/core/src/employee-recurring-expense/dto/create-employee-recurring-expense.dto.ts
  packages/core/src/employee-recurring-expense/dto/employee-recurring-expense.dto.ts
  packages/core/src/employee-recurring-expense/dto/index.ts
  packages/core/src/employee-recurring-expense/dto/update-employee-recurring-expense.dto.ts
  packages/core/src/employee-recurring-expense/employee-recurring-expense.controller.ts
  packages/core/src/employee-recurring-expense/employee-recurring-expense.entity.ts
  packages/core/src/employee/dto/employee-feature.dto.ts
  packages/core/src/employee/dto/index.ts
Labels: validators, Changes requested
