Repository ever-co/ever-gauzy, pull requests merged in 2022-01, with the labels that each got.

#3920 Fix/#3299 Knex Timeout acquiring a connection
  apps/desktop-timer/src/index.ts
  apps/desktop/src/index.ts
  packages/desktop-libs/src/lib/desktop-database-migration.ts
  packages/desktop-libs/src/lib/desktop-ipc.ts
  packages/desktop-libs/src/lib/desktop-timer-activity.ts
  packages/desktop-libs/src/lib/desktop-timer.ts
  tools/build/webpack.config.js
Labels: hold

#3983 Fix/ WIP Employee Own Profile Edit (Don't Merge)
  apps/gauzy/src/app/@core/services/employees.service.ts
  apps/gauzy/src/app/@shared/employee/employee-rates/employee-rates.component.html
  apps/gauzy/src/app/@shared/employee/employee-rates/employee-rates.component.ts
  apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.html
  apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-profile.component.ts
  apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.ts
  apps/gauzy/src/app/pages/employees/employees.component.ts
  packages/contracts/src/employee.model.ts
  packages/contracts/src/entity-with-members.model.ts
  packages/contracts/src/organization-department.model.ts
  packages/contracts/src/organization-employment-type.model.ts
  packages/core/src/employee/dto/employment.dto.ts
  packages/core/src/employee/dto/hiring.dto.ts
  packages/core/src/employee/dto/index.ts
  packages/core/src/employee/dto/network.dto.ts
  packages/core/src/employee/dto/rates.dto.ts
  packages/core/src/employee/dto/update-profile.dto.ts
  packages/core/src/employee/employee.controller.ts
  packages/core/src/organization-department/dto/create-organization-department.dto.ts
  packages/core/src/organization-department/dto/index.ts
  packages/core/src/organization-department/organization-department.entity.ts
  packages/core/src/organization-employment-type/dto/create-organization-employement-type.dto.ts
  packages/core/src/organization-employment-type/dto/index.ts
  packages/core/src/organization-employment-type/organization-employment-type.entity.ts
Labels: hold

#4001 Fix/#3937 Edit User Profile (fixed email edit)
  apps/gauzy/src/app/@shared/user/edit-profile-form/edit-profile-form.component.ts
Labels: type: bug :bug:

#4013 Feature :: Implemented dto validators for auth routes
  packages/core/src/auth/auth.controller.ts
  packages/core/src/auth/dto/has-role-query.dto.ts
  packages/core/src/auth/dto/index.ts
  packages/core/src/user/dto/create-user.dto.ts
  packages/core/src/user/dto/register-user.dto.ts
Labels: type: enhancement ✨, validators

#4022 Feat / Implemented data dto validations for employee endpoints
  packages/core/src/employee/dto/create-employee.dto.ts
  packages/core/src/employee/dto/employee-input.dto.ts
  packages/core/src/employee/dto/update-employee.dto.ts
  packages/core/src/employee/dto/user-input-dto.ts
  packages/core/src/employee/employee.controller.ts
  packages/core/src/employee/pipes/employee-transformer.pipe.ts
Labels: validators

#4038 Feat / Implemented dto validation for updating email
  packages/core/src/email/dto/index.ts
  packages/core/src/email/dto/update-email.dto.ts
  packages/core/src/email/email.controller.ts
Labels: validators

#4032 Feat / implemented dto validations for task endpoints #4026
  packages/contracts/src/task-entity.model.ts
  packages/core/src/database/migrations/1643201180573-AlterTaskTable.ts
  packages/core/src/tasks/dto/create-task.dto.ts
  packages/core/src/tasks/dto/index.ts
  packages/core/src/tasks/dto/task.dto.ts
  packages/core/src/tasks/dto/update-task.dto.ts
  packages/core/src/tasks/task.controller.ts
  packages/core/src/tasks/task.entity.ts
Labels: validators, Changes requested

#4040 Feat / Implemented dto validations for candidate endpoints
  apps/gauzy/src/app/pages/candidates/candidates.component.ts
  apps/gauzy/src/app/pages/employees/employees.component.ts
  packages/core/src/candidate/candidate.controller.ts
  packages/core/src/candidate/commands/handlers/candidate.update.handler.ts
  packages/core/src/candidate/dto/candidate-bulk-input.dto.ts
  packages/core/src/candidate/dto/create-candidate.dto.ts
  packages/core/src/candidate/dto/index.ts
  packages/core/src/candidate/dto/update-candidate.dto.ts
  packages/core/src/employee/dto/create-employee.dto.ts
  packages/core/src/employee/dto/employee-bulk-input.dto.ts
  packages/core/src/employee/dto/employee-input.dto.ts
  packages/core/src/employee/dto/index.ts
  packages/core/src/employee/employee.controller.ts
  packages/core/src/employee/pipes/employee-transformer.pipe.ts
  packages/core/src/shared/pipes/bulk-body-load-transform.pipe.ts
  packages/core/src/shared/pipes/index.ts
  packages/core/src/user/dto/create-user.dto.ts
  packages/core/src/user/user.subscriber.ts
Labels: validators, Changes requested

#4042 Feat / Implemented dto validations for equipments endpoints
  packages/core/src/equipment/dto/create-equipment.dto.ts
  packages/core/src/equipment/dto/equipment.dto.ts
  packages/core/src/equipment/dto/index.ts
  packages/core/src/equipment/dto/update-equipement.dto.ts
  packages/core/src/equipment/equipment.controller.ts
  packages/core/src/equipment/equipment.service.ts
  packages/core/src/tenant/dto/index.ts
  packages/core/src/tenant/dto/tenant.dto.ts
Labels: validators, Changes requested

#4045 Feat / Implemented dto validations for products end point
  packages/core/src/product/dto/create-product.dto.ts
  packages/core/src/product/dto/index.ts
  packages/core/src/product/dto/product.dto.ts
  packages/core/src/product/dto/update-product.dto.ts
  packages/core/src/product/product.controller.ts
Labels: validators, Changes requested
