Repository ever-co/ever-gauzy, pull requests merged in 2023-08, with the labels that each got.

#6651 6616 quick setting should also be closed clicked outside the dialog
  apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.component.html
  apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.component.ts
  apps/gauzy/src/app/@theme/components/theme-sidebar/theme-settings/theme-settings.module.ts
Labels: changes approved 🚀

#6664 Desktop download link changed
  .env.compose
  .env.docker
  .env.local
  .env.sample
  .scripts/configure.ts
  .scripts/env.ts
  apps/gauzy/src/app/@shared/report/daily-grid/daily-grid.component.html
  apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.html
  apps/gauzy/src/app/@shared/time-tracker/time-tracker/time-tracker.component.ts
  apps/gauzy/src/app/@theme/components/user-menu/user-menu.component.ts
  apps/gauzy/src/assets/i18n/bg.json
  apps/gauzy/src/assets/i18n/en.json
  apps/gauzy/src/assets/i18n/es.json
  apps/gauzy/src/assets/i18n/fr.json
  apps/gauzy/src/assets/i18n/he.json
  apps/gauzy/src/assets/i18n/ru.json
  apps/gauzy/src/environments/model.ts
Labels: Changes requested

#6701 feat: Added TEAMS source for time tracking
  packages/contracts/src/timesheet.model.ts
Labels: enhancement

#6773 fix: #6772 Added support of Multiple Team invitations
  packages/core/src/core/utils.ts
  packages/core/src/invite/invite.service.ts
Labels: bug
