Repository ever-co/ever-gauzy, pull requests merged in 2023-02, with the labels that each got.

#5631 [MegaLinter] Apply linters automatic fixes
  packages/contracts/src/employee-phone.model.ts
  packages/contracts/src/index.ts
  packages/contracts/src/user.model.ts
  packages/core/src/database/migrations/1675240711524-CreateEmployeePhoneTable.ts
  packages/core/src/database/migrations/1675241589518-AlterUserTable.ts
  packages/core/src/employee-phone/employee-phone.entity.ts
  packages/core/src/employee/employee.entity.ts
  packages/core/src/user/user.entity.ts
Labels: bot

#5676 [MegaLinter] Apply linters automatic fixes
  packages/desktop-libs/src/lib/desktop-ipc.ts
  packages/desktop-libs/src/lib/desktop-timer.ts
  packages/desktop-libs/src/lib/offline/dao/timer.dao.ts
  packages/desktop-libs/src/lib/offline/databases/migrations/20230207104126_alter-table-timers.ts
  packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
Labels: bot

#5677 [MegaLinter] Apply linters automatic fixes
  packages/desktop-libs/src/lib/desktop-ipc.ts
  packages/desktop-libs/src/lib/desktop-timer.ts
  packages/desktop-libs/src/lib/offline/databases/migrations/20230208165526_alter-table-timers.ts
  packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
  packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
Labels: bot

#5689 [MegaLinter] Apply linters automatic fixes
  apps/gauzy/src/app/@theme/components/header/selectors/date-range-picker/date-range-picker.component.ts
Labels: bot

#5696 [MegaLinter] Apply linters automatic fixes
  apps/gauzy/src/app/pages/dashboard/team/team-member/team-member.component.ts
  apps/gauzy/src/app/pages/dashboard/team/team.component.ts
  packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.component.ts
  packages/desktop-ui-lib/src/lib/time-tracker/time-tracker.service.ts
Labels: bot

#5733 fix: #5703 no header title on vendors
  apps/gauzy/src/app/pages/vendors/vendors.component.html
  apps/gauzy/src/app/pages/vendors/vendors.component.scss
  apps/gauzy/src/app/pages/vendors/vendors.component.ts
  apps/gauzy/src/assets/i18n/en.json
Labels: Changes requested

#5790 fix: #5730 currency dropdown cutoff
  apps/gauzy/src/app/@shared/currency/currency.component.html
  apps/gauzy/src/app/@shared/currency/currency.component.scss
  apps/gauzy/src/app/@shared/currency/currency.component.ts
Labels: changes approved 🚀

#5804 fix: #5702 multiple vendors created
  apps/gauzy/src/app/pages/vendors/vendors.component.html
  apps/gauzy/src/app/pages/vendors/vendors.component.ts
Labels: changes approved 🚀
