Repository ever-co/ever-gauzy, pull requests merged in 2023-03, with the labels that each got.

#5843 fix: #5806 proposal template default
  apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.html
  apps/gauzy/src/app/pages/jobs/proposal-template/proposal-template/proposal-template.component.ts
  apps/gauzy/src/assets/i18n/en.json
  packages/core/src/employee-proposal-template/employee-proposal-template.service.ts
Labels: changes approved 🚀

#5940 [MegaLinter] Apply linters automatic fixes
  github_conf/branch_protection_rules.json
  packages/config/src/environments/environment.prod.ts
  packages/config/src/environments/environment.ts
  packages/contracts/src/candidate.model.ts
  packages/contracts/src/employee.model.ts
  packages/contracts/src/equipment-sharing.model.ts
  packages/contracts/src/goals.model.ts
  packages/contracts/src/invite.model.ts
  packages/contracts/src/organization-team-employee-model.ts
  packages/contracts/src/organization-team-join-request.model.ts
  packages/contracts/src/organization-team.model.ts
  packages/contracts/src/request-approval-team.model.ts
  packages/contracts/src/request-approval.model.ts
  packages/contracts/src/tag.model.ts
  packages/contracts/src/task-priority.model.ts
  packages/contracts/src/task-size.model.ts
  packages/contracts/src/task-status.model.ts
  packages/contracts/src/task.model.ts
  packages/contracts/src/timesheet.model.ts
  packages/contracts/src/user.model.ts
  packages/core/src/app.module.ts
  packages/core/src/database/migrations/1678187685289-CreateOrganizationTeamJoinRequestTable.ts
  packages/core/src/organization-team-join-request/organization-team-join-request.controller.ts
  packages/core/src/organization-team-join-request/organization-team-join-request.entity.ts
  packages/core/src/organization-team-join-request/organization-team-join-request.module.ts
  packages/core/src/organization-team-join-request/organization-team-join-request.service.ts
  packages/core/src/organization-team-join-request/organization-team-join-request.subscriber.ts
Labels: bot

#5924 Feat :: #5741 Join Public Team Request
  .cspell.json
Labels: hold

#5976 [MegaLinter] Apply linters automatic fixes
  packages/contracts/src/organization-team-join-request.model.ts
  packages/contracts/src/organization-team.model.ts
Labels: bot

#5980 [MegaLinter] Apply linters automatic fixes
  packages/contracts/src/organization-team-join-request.model.ts
Labels: bot

#6085 [MegaLinter] Apply linters automatic fixes
  apps/gauzy/src/app/pages/jobs/jobs-routing.module.ts
  packages/contracts/src/role-permission.model.ts
  packages/contracts/src/role.model.ts
  packages/core/src/database/migrations/1644312012849-RolePermissionsReload.ts
  packages/core/src/database/migrations/1679765443208-MigrateRolePermisisons.ts
  packages/core/src/role-permission/default-role-permissions.ts
  packages/core/src/role-permission/role-permission.seed.ts
  packages/core/src/role-permission/utils.ts
  packages/core/src/role/role.seed.ts
  packages/core/src/role/role.service.ts
Labels: bot

#6045 feat:#6002 WIP: Current User Invitation list API, Accept/Reject API
  packages/contracts/src/invite.model.ts
  packages/core/src/auth/auth.module.ts
  packages/core/src/invite/dto/index.ts
  packages/core/src/invite/invite.controller.ts
  packages/core/src/invite/invite.module.ts
  packages/core/src/invite/invite.service.ts
Labels: hold

#6140 [MegaLinter] Apply linters automatic fixes
  packages/core/src/database/migrations/1680172332764-AddIndexesColumnsToTheTimeLogTable.ts
  packages/core/src/time-tracking/time-log/time-log.entity.ts
Labels: bot

#6124 Feat: Added Task Statistics in Organization Team API
  packages/contracts/src/timesheet-statistics.model.ts
  packages/core/src/organization-team/dto/organization-team-statistic.dto.ts
  packages/core/src/organization-team/organization-team.module.ts
  packages/core/src/organization-team/queries/get-organization-team-statistic.query.ts
  packages/core/src/organization-team/queries/handlers/get-organization-team-statistic.handler.ts
  packages/core/src/public-share/team/dto/public-team-query.dto.ts
  packages/core/src/time-tracking/statistic/statistic.service.ts
Labels: hold
